/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimationText: typeof import('./src/components/AnimationText/index.vue')['default']
    CalenderModal: typeof import('./src/components/Modal/CalenderModal.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    InputText: typeof import('./src/components/Form/InputText.vue')['default']
    LeftArrowIcon: typeof import('./src/components/icons/LeftArrowIcon.vue')['default']
    Modal: typeof import('./src/components/Modal/index.vue')['default']
    ModalWrapper: typeof import('./src/components/Modal/ModalWrapper.vue')['default']
    NotFound: typeof import('./src/components/NotFound/index.vue')['default']
    RightArrowIcon: typeof import('./src/components/icons/RightArrowIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Layout/Sidebar/index.vue')['default']
    TimePicker: typeof import('./src/components/Form/TimePicker.vue')['default']
    Topbar: typeof import('./src/components/Layout/Topbar/index.vue')['default']
  }
}
